version: '3.8'

services:
  mysql_base:
    image: mysql:8.0
    container_name: mysql_base
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wonho
      MYSQL_DATABASE: test
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app_network
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'root',
          '-p$$MYSQL_ROOT_PASSWORD',
        ]
      interval: 30s
      timeout: 10s
      retries: 5

  tool_base:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tool_base
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql_base
      - DB_USER=root
      - DB_PASSWORD=wonho
      - DB_NAME=test
      - DB_PORT=3306
    depends_on:
      mysql_base:
        condition: service_healthy
    networks:
      - app_network
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - node_modules:/app/node_modules

volumes:
  mysql_data:
    driver: local
  node_modules:
    driver: local

networks:
  app_network:
    driver: bridge
